futbol/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urls.py
from django.urls import path 

from .views import *

app_name = 'blog'


urlpatterns = [
    path('', listar_publicaciones, name='listar_publicaciones'),
    path('<uuid:pub>/', ver_publicacion, name='ver_publicacion'),
    path('categoria/<int:categoria>/', ver_publicaciones_categoria, name='ver_publicaciones_categoria')
]

models.py
from django.db import models
from django.contrib.auth.models import User

import uuid 


class Categoria(models.Model):
    descripcion = models.CharField(max_length=60,
                                    help_text='Descripcion de la Categoria')
    autor = models.ForeignKey(User,
                                on_delete=models.PROTECT,
                                help_text='Seleccione el autor de la categoria')
    
    def __str__(self):
        return self.descripcion


class Publicacion(models.Model):
    id = models.UUIDField(primary_key= True, editable=False, default=uuid.uuid4)
    titulo = models.CharField(max_length=200,
                                help_text='Escriba el titulo de la publicacion')
    contenido = models.TextField(max_length=20000,
                                 help_text='Escriba el contenido de la publicacion')
    autor = models.ForeignKey(User,
                                on_delete=models.PROTECT,
                                help_text='Seleccione el autor de la categoria')
    f_pub = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')
    categorias = models.ManyToManyField(Categoria,
                                        help_text='Seleccione las categorias')
    
    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Publicacion'  
        verbose_name_plural = 'Publicaciones'
        ordering = ['-f_pub'] 


views.py
from django.shortcuts import render

from .models import *


def listar_publicaciones(request):
    news = Publicacion.objects.all().order_by('-f_pub')
    return render(request, './post/index.html', {'news':news})

def ver_publicacion(request, pub):
    publicacion = Publicacion.objects.get(id = pub)
    return render(request, './post/ver.html', {'publicacion':publicacion})

def ver_publicaciones_categoria(request, categoria):
    categoria = Categoria.objects.get(id = categoria)
    return render(request, './post/index.html', {'categoria':categoria})


templates/post/index.html
{% extends "base.html" %}

{% block titulo %}Moto Cross{% endblock  %}

{% block cuerpo %}
    {% if categoria %}
        <h1>publicaciones en {{ categoria.descripcion }}</h1>
        {% for new in categoria.publicacion_set.all %}
            <div>
                <h2><a href='{% url 'blog:ver_publicacion' new.id %}'>{{ new.titulo }}</a></h2> <hr>
                <p>
                     {{ new.contenido|truncatechars:250 }} <br>
                     {{ new.autor.get_full_name }} publicado: {{ new.f_pub }}
                </p>
            </div>
             {% endfor %}

         {% else %}

            {% for new in news %}
                <div>
                    <h2><a href='{% url 'blog:ver_publicacion' new.id %}'>{{ new.titulo }}</a></h2> <hr>
                    <p>
                        {{ new.contenido|truncatechars:250 }} <br>
                        {{ new.autor.get_full_name }} publicado: {{ new.f_pub }}

                        {%for categoria in new.categorias.all %}
                             <a href="">{{ categoria.descrpcion}}</a>
                        {% endfor %}

                    </p>
                </div>
            {% endfor %}
         {% endif %}

{% endblock  %}

templates/post/ver.html
{% extends 'base.html' %}

{% block titulo %} {{ pub.titulo|truncatechars:30 }}Moto Cross{% endblock  %}

{% block cuerpo %}
    
        <h1>{{ publicacion.titulo }}</h1>
        <p align="justify">
        <p> {{ publicacion.contenido }} </p>
        {{ publicacion.autor.get_full_name }} publicado: {{ publicacion.f_pub}}
<a href="carpeta/web.html"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS5Kkh5C-UhrVybX0nXVfzQcx9e0kA-nHNFUA&usqp=CAU"></a> 
<nav>
         <div class="nav-wrapper blue darken-4">
        
          <a href="#" data-target="menu-chico" class="sidenav-trigger"><i class="material-icons">menu</i></a>
       
          <ul id="nav-mobile" class="rigth hide-on-med-and-down">
            <li><a href="">Motos</a></li>
            <li><a href="">Carreras</a></li>
            <li><a href="">motociclistas</a></li>
            <li><a href="">equipacion de motos</a></li>
            <li><a href="">autopistas</a></li>
          </ul>
        </div>
</nav>

<div>
 <a href="https://www.addtoany.com/share#url=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;title=" target="_blank"><img src="https://static.addtoany.com/buttons/a2a.svg" width="32" height="32" style="background-color:royalblue"></a> 
 <a href="https://www.addtoany.com/add_to/facebook?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/facebook.svg" width="32" height="32" style="background-color:royalblue"></a> 
 <a href="https://www.addtoany.com/add_to/twitter?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/twitter.svg" width="32" height="32" style="background-color:royalblue"></a> 
 <a href="https://www.addtoany.com/add_to/email?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/email.svg" width="32" height="32" style="background-color:royalblue"></a> 
 </div>
<!-- addtoany END -->

      {% endblock %}